#!/bin/bash

set -a

# export env vars
source .env

sudo -u postgres bash -c "psql -h $HOST -c \"
CREATE DATABASE $DATABASE;
\""

sudo -u postgres bash -c "psql -h $HOST -d $DATABASE -c \"
CREATE SCHEMA IF NOT EXISTS $IMDB_SCHEMA;
\""

sudo -u postgres bash -c "psql -h $HOST -d $DATABASE -U postgres -p $PORT -a -f projects/imdb/sql/create_tables.sql"


sudo -u postgres bash -c "psql -h $HOST -d $DATABASE -U postgres -p $PORT -c \"
CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';


GRANT USAGE, CREATE ON SCHEMA $IMDB_SCHEMA TO $POSTGRES_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $IMDB_SCHEMA TO $POSTGRES_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA $IMDB_SCHEMA
    GRANT ALL PRIVILEGES ON TABLES TO $POSTGRES_USER;


GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA $IMDB_SCHEMA TO $POSTGRES_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA $IMDB_SCHEMA GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $POSTGRES_USER;
\""


# deletes env vars
set +a

# sudo -u postgres bash -c "psql -h $HOST -d $DATABASE -c \"
# # GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
# # ON ALL TABLES
# # IN SCHEMA $IMDB_SCHEMA
# # TO $POSTGRES_USER;
# ALTER DATABASE $DATABASE OWNER TO $POSTGRES_USER;
# \""




# GRANT ALL PRIVILEGES ON SCHEMA $IMDB_SCHEMA TO $POSTGRES_USER;
# ALTER DATABASE $DATABASE OWNER TO $POSTGRES_USER;

# GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
#     ON ALL TABLES IN SCHEMA $IMDB_SCHEMA
#     TO $POSTGRES_USER;